import type { DatasetSummary } from "./columns";

// Hand-written summaries of the demo datasets in public/data/, with figures
// taken from the files themselves. See docs/DATA.md for what each column means.
// Category values are in natural order (D-015): calendar order for weekdays and
// seasons, otherwise the order they first appear in the file.

export const bikesSummary = {
  rowCount: 25262,
  columns: [
    {
      name: "start_time",
      label: "Start time",
      kind: "date",
      distinct: 16684,
      nulls: 0,
      min: "2026-01-16T00:07",
      max: "2026-05-31T23:57",
      examples: ["2026-01-16T00:07", "2026-01-16T00:13", "2026-01-16T00:31", "2026-01-16T00:35", "2026-01-16T00:48"],
    },
    {
      name: "date",
      label: "Date",
      kind: "date",
      distinct: 31,
      nulls: 0,
      min: "2026-01-16",
      max: "2026-05-31",
      examples: ["2026-01-16", "2026-01-17", "2026-01-18", "2026-01-19", "2026-01-20"],
    },
    {
      name: "weekday",
      label: "Day of the week",
      kind: "category",
      distinct: 7,
      nulls: 0,
      values: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    },
    { name: "day_type", label: "Day type", kind: "category", distinct: 2, nulls: 0, values: ["Weekday", "Weekend"] },
    { name: "hour", label: "Hour of day", kind: "number", distinct: 24, nulls: 0, min: 0, max: 23, examples: [0, 1, 2, 3, 4] },
    { name: "season", label: "Season", kind: "category", distinct: 2, nulls: 0, values: ["Winter", "Spring"] },
    {
      name: "start_station",
      label: "Start station",
      kind: "category",
      distinct: 805,
      nulls: 0,
      examples: [
        "Westminster University, Marylebone",
        "Woodstock Grove, Shepherd's Bush",
        "Baylis Road, Waterloo",
        "Dorset Square, Marylebone",
        "Soho Square, Soho",
      ],
    },
    {
      name: "start_area",
      label: "Start area",
      kind: "category",
      distinct: 126,
      nulls: 0,
      values: [
        "Marylebone", "Shepherd's Bush", "Waterloo", "Soho", "Holborn", "Paddington", "Covent Garden", "West End",
        "Monument", "South Bank", "Bloomsbury", "Camden Town", "Brook Green", "Westminster", "South Kensington",
        "Shoreditch", "West Chelsea", "Moorgate", "Shadwell", "Fulham", "Stockwell", "Euston", "Putney", "Walham Green",
        "Pimlico", "Hammersmith", "Battersea Park", "Earl's Court", "Hackney Central", "Walworth", "Bermondsey",
        "Borough", "Stepney", "Olympia", "Bayswater", "Kings Cross", "Clapham Junction", "Sands End", "Wapping",
        "Battersea", "West Kensington", "Mile End", "Clapham Common", "Notting Hill", "Hoxton", "Wandsworth",
        "Kensington", "Strand", "Southwark", "Aldgate", "Poplar", "Vauxhall", "St. Paul's", "Bow", "Knightsbridge",
        "Parsons Green", "Kennington", "St. John's Wood", "Whitechapel", "Rotherhithe", "Clapham", "Chelsea",
        "Kensington Gardens", "Bethnal Green", "Oval", "Victoria Park", "The Borough", "Liverpool Street", "Victoria",
        "North Kensington", "Haggerston", "St. Luke's", "Elephant & Castle", "The Regent's Park_OLD", "Bank",
        "Fitzrovia", "Barbican", "Sloane Square", "Finsbury", "Mayfair", "Hyde Park", "The Regent's Park",
        "Shad Thames", "White City", "Portobello", "Clerkenwell", "Canary Wharf", "Bankside", "Avondale",
        "Wandsworth Road", "Liverpool Street_OLD", "Angel", "Nine Elms", "London Bridge", "Maida Vale", "Millwall",
        "Guildhall", "Old Ford", "Limehouse", "Blackwall", "King's Cross", "Cubitt Town", "Parson's Green", "Tower",
        "St. James's", "De Beauvoir Town", "Temple", "St Pauls", "Maida Hill", "Farringdon",
        "Queen Elizabeth Olympic Park", "Somers Town", "Brixton", "Holland Park", "Belgravia", "West Brompton",
        "St Lukes", "Wandsworth Common", "Clapham South", "Hackney Wick", "Stratford", "Westbourne", "Ladbroke Grove",
        "St.John's Wood", "East Putney", "Blackwall Tunnel",
      ],
    },
    {
      name: "start_lat",
      label: "Start latitude",
      kind: "number",
      distinct: 493,
      nulls: 130,
      min: 51.453,
      max: 51.5494,
      examples: [51.5225, 51.504, 51.5014, 51.5226, 51.5156],
    },
    {
      name: "start_lon",
      label: "Start longitude",
      kind: "number",
      distinct: 666,
      nulls: 130,
      min: -0.2368,
      max: 0.005,
      examples: [-0.1549, -0.2174, -0.1107, -0.1611, -0.1323],
    },
    {
      name: "end_station",
      label: "End station",
      kind: "category",
      distinct: 806,
      nulls: 0,
      examples: [
        "Fulham Park Road, Fulham",
        "Blythe Road, Olympia",
        "New Spring Gardens Walk, Vauxhall",
        "St. John's Wood Road, St. John's Wood",
        "Millbank Tower, Pimlico",
      ],
    },
    {
      name: "end_area",
      label: "End area",
      kind: "category",
      distinct: 126,
      nulls: 0,
      values: [
        "Fulham", "Olympia", "Vauxhall", "St. John's Wood", "Pimlico", "Somers Town", "Bayswater", "Stepney", "Clapham",
        "Southwark", "Euston", "Marylebone", "Wapping", "Shepherd's Bush", "Strand", "Putney", "Finsbury",
        "Walham Green", "Guildhall", "Clapham Junction", "Clerkenwell", "Canary Wharf", "Wandsworth", "West Kensington",
        "Victoria", "Temple", "Bloomsbury", "Chelsea", "Bethnal Green", "Walworth", "Bank", "Haggerston", "St. Luke's",
        "Holborn", "Paddington", "Camden Town", "Sands End", "St. Paul's", "The Regent's Park", "Westminster",
        "West End", "Hammersmith", "Mayfair", "Clapham South", "St. James's", "Bow", "Soho", "Kensington",
        "Shad Thames", "Monument", "Liverpool Street", "Poplar", "Shoreditch", "The Borough", "Fitzrovia",
        "Knightsbridge", "Parson's Green", "Aldgate", "St Lukes", "Farringdon", "Bermondsey", "Barbican",
        "King's Cross", "Nine Elms", "Parsons Green", "Earl's Court", "Limehouse", "Battersea Park", "North Kensington",
        "South Kensington", "Notting Hill", "Waterloo", "Kennington", "Clapham Common", "Moorgate", "West Chelsea",
        "Elephant & Castle", "Mile End", "Stockwell", "Covent Garden", "Whitechapel", "Tower", "Portobello",
        "West Brompton", "White City", "Liverpool Street_OLD", "Oval", "Ladbroke Grove", "London Bridge", "Hyde Park",
        "Kensington Gardens", "Rotherhithe", "Queen Elizabeth Olympic Park", "Hoxton", "Battersea", "Kings Cross",
        "Angel", "South Bank", "Shadwell", "Millwall", "Blackwall", "Wandsworth Road", "Cubitt Town", "Brixton",
        "Westbourne", "Hackney Central", "Bankside", "De Beauvoir Town", "Old Ford", "Borough", "Holland Park",
        "Victoria Park", "Maida Vale", "Stratford", "Brook Green", "Maida Hill", "Avondale", "Belgravia",
        "Hackney Wick", "Sloane Square", "East Putney", "The Regent's Park_OLD", "St Pauls", "St.John's Wood",
        "Wandsworth Common", "Blackwall Tunnel",
      ],
    },
    {
      name: "end_lat",
      label: "End latitude",
      kind: "number",
      distinct: 493,
      nulls: 125,
      min: 51.453,
      max: 51.5494,
      examples: [51.4735, 51.4969, 51.4878, 51.5273, 51.4919],
    },
    {
      name: "end_lon",
      label: "End longitude",
      kind: "number",
      distinct: 667,
      nulls: 125,
      min: -0.2368,
      max: 0.005,
      examples: [-0.2078, -0.2135, -0.1228, -0.1747, -0.1257],
    },
    { name: "round_trip", label: "Round trip", kind: "category", distinct: 2, nulls: 0, values: ["No", "Yes"] },
    {
      name: "duration_min",
      label: "Duration (min)",
      kind: "number",
      distinct: 930,
      nulls: 0,
      min: 0.9,
      max: 1365.5,
      examples: [40.1, 26.2, 6.5, 6, 9],
    },
    { name: "bike_type", label: "Bike type", kind: "category", distinct: 2, nulls: 0, values: ["E-bike", "Classic"] },
  ],
  sampleRows: [
    {
      start_time: "2026-01-16T00:07",
      date: "2026-01-16",
      weekday: "Fri",
      day_type: "Weekday",
      hour: 0,
      season: "Winter",
      start_station: "Westminster University, Marylebone",
      start_area: "Marylebone",
      start_lat: 51.5225,
      start_lon: -0.1549,
      end_station: "Fulham Park Road, Fulham",
      end_area: "Fulham",
      end_lat: 51.4735,
      end_lon: -0.2078,
      round_trip: "No",
      duration_min: 40.1,
      bike_type: "E-bike",
    },
    {
      start_time: "2026-01-16T00:13",
      date: "2026-01-16",
      weekday: "Fri",
      day_type: "Weekday",
      hour: 0,
      season: "Winter",
      start_station: "Woodstock Grove, Shepherd's Bush",
      start_area: "Shepherd's Bush",
      start_lat: 51.504,
      start_lon: -0.2174,
      end_station: "Blythe Road, Olympia",
      end_area: "Olympia",
      end_lat: 51.4969,
      end_lon: -0.2135,
      round_trip: "No",
      duration_min: 26.2,
      bike_type: "Classic",
    },
    {
      start_time: "2026-01-16T00:13",
      date: "2026-01-16",
      weekday: "Fri",
      day_type: "Weekday",
      hour: 0,
      season: "Winter",
      start_station: "Baylis Road, Waterloo",
      start_area: "Waterloo",
      start_lat: 51.5014,
      start_lon: -0.1107,
      end_station: "New Spring Gardens Walk, Vauxhall",
      end_area: "Vauxhall",
      end_lat: 51.4878,
      end_lon: -0.1228,
      round_trip: "No",
      duration_min: 6.5,
      bike_type: "Classic",
    },
  ],
} satisfies DatasetSummary;

export const gelatoSummary = {
  rowCount: 22964,
  columns: [
    {
      name: "date",
      label: "Date",
      kind: "date",
      distinct: 729,
      nulls: 0,
      min: "2024-01-01",
      max: "2025-12-31",
      examples: ["2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04", "2024-01-05"],
    },
    {
      name: "weekday",
      label: "Day of the week",
      kind: "category",
      distinct: 7,
      nulls: 0,
      values: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    },
    {
      name: "shop",
      label: "Shop",
      kind: "category",
      distinct: 5,
      nulls: 0,
      values: ["Covent Garden", "Hampstead Heath", "Canary Wharf", "Brixton", "Richmond Riverside"],
    },
    {
      name: "flavour",
      label: "Flavour",
      kind: "category",
      distinct: 7,
      nulls: 0,
      values: [
        "Pistachio",
        "Stracciatella",
        "Dark Chocolate",
        "Salted Caramel",
        "Amalfi Lemon",
        "Alphonso Mango",
        "Earl Grey",
      ],
    },
    { name: "flavour_type", label: "Flavour type", kind: "category", distinct: 2, nulls: 0, values: ["Gelato", "Sorbet"] },
    { name: "scoops", label: "Scoops", kind: "number", distinct: 274, nulls: 0, min: 1, max: 327, examples: [70, 69, 75, 61, 33] },
    {
      name: "revenue_gbp",
      label: "Revenue (£)",
      kind: "number",
      distinct: 1320,
      nulls: 0,
      min: 3.6,
      max: 1344.15,
      examples: [301, 269.1, 292.5, 237.9, 128.7],
    },
    {
      name: "max_temp_c",
      label: "Peak temperature (°C)",
      kind: "number",
      distinct: 237,
      nulls: 0,
      min: 3.2,
      max: 34.8,
      examples: [7.4, 6.8, 6.6, 8.3, 11.7],
    },
    { name: "rain_mm", label: "Rainfall (mm)", kind: "number", distinct: 107, nulls: 0, min: 0, max: 34.3, examples: [0, 1.4, 2.2, 3.4, 0.6] },
    { name: "weather", label: "Weather", kind: "category", distinct: 3, nulls: 0, values: ["Cloudy", "Rain", "Sunny"] },
    { name: "school_holiday", label: "School holiday", kind: "category", distinct: 2, nulls: 0, values: ["Yes", "No"] },
    { name: "bank_holiday", label: "Bank holiday", kind: "category", distinct: 2, nulls: 0, values: ["Yes", "No"] },
  ],
  sampleRows: [
    {
      date: "2024-01-01",
      weekday: "Mon",
      shop: "Covent Garden",
      flavour: "Pistachio",
      flavour_type: "Gelato",
      scoops: 70,
      revenue_gbp: 301,
      max_temp_c: 7.4,
      rain_mm: 0,
      weather: "Cloudy",
      school_holiday: "Yes",
      bank_holiday: "Yes",
    },
    {
      date: "2024-01-01",
      weekday: "Mon",
      shop: "Covent Garden",
      flavour: "Stracciatella",
      flavour_type: "Gelato",
      scoops: 69,
      revenue_gbp: 269.1,
      max_temp_c: 7.4,
      rain_mm: 0,
      weather: "Cloudy",
      school_holiday: "Yes",
      bank_holiday: "Yes",
    },
    {
      date: "2024-01-01",
      weekday: "Mon",
      shop: "Covent Garden",
      flavour: "Dark Chocolate",
      flavour_type: "Gelato",
      scoops: 75,
      revenue_gbp: 292.5,
      max_temp_c: 7.4,
      rain_mm: 0,
      weather: "Cloudy",
      school_holiday: "Yes",
      bank_holiday: "Yes",
    },
  ],
} satisfies DatasetSummary;
